import { fileURLToPath, URL } from 'node:url'

import { defineConfig } from 'vitepress'

// Generated by `scripts/generate-docs.mjs` — one VitePress sidebar *group* per
// component category (the same grouping shopify.dev uses), each holding the
// component reference pages under `docs/components/`. The codegen script owns
// this file wholesale, so nothing here needs touching beyond re-running
// `npm run docs:generate`.
import componentsSidebar from './components-sidebar.json'

// https://vitepress.dev/reference/site-config
export default defineConfig({
  title: 'polaris-vue',
  description: 'Typed Vue 3 wrapper components for Shopify Polaris web components.',

  head: [
    ['link', { rel: 'icon', href: '/favicon.ico' }],
    // Loads the real Polaris custom element definitions so that live examples
    // in the docs (and the components used to render this site itself) work
    // exactly as they would in a consuming app.
    ['script', { src: 'https://cdn.shopify.com/shopifycloud/polaris.js' }],
  ],

  // Component reference pages may not exist yet (they're generated by a
  // separate script), so avoid failing the build on links to them.
  ignoreDeadLinks: true,

  vue: {
    template: {
      compilerOptions: {
        // Polaris web components (`<s-button>`, `<s-text-field>`, ...) are
        // custom elements, not Vue components — don't warn/resolve them as such.
        isCustomElement: (tag) => tag.startsWith('s-'),
      },
    },
  },

  vite: {
    resolve: {
      alias: {
        // Lets docs pages `import { SButton } from '@lib'` directly from source.
        '@lib': fileURLToPath(new URL('../../src/lib', import.meta.url)),
      },
    },
  },

  themeConfig: {
    // https://vitepress.dev/reference/default-theme-config
    nav: [
      { text: 'Guide', link: '/guide/getting-started' },
      { text: 'Components', link: '/components/' },
    ],

    sidebar: [
      {
        text: 'Guide',
        items: [
          { text: 'Getting started', link: '/guide/getting-started' },
          { text: 'Known quirks & gotchas', link: '/guide/quirks' },
          { text: 'All components', link: '/components/' },
        ],
      },
      // Spread rather than nested under a single "Components" parent: one more
      // level of nesting would push every component three deep and force two
      // clicks to reach any page.
      ...componentsSidebar,
    ],

    // Built-in MiniSearch index, built at build time from the full rendered text
    // of every page — so prop names, event names and prose are all searchable, not
    // just component titles. No external service, no runtime network call.
    search: {
      provider: 'local',
      options: {
        detailedView: true,
      },
    },

    outline: [2, 3],

    footer: {
      message: 'Released under the MIT License.',
      copyright: 'Wrappers around Shopify Polaris web components — not affiliated with Shopify.',
    },

    socialLinks: [{ icon: 'github', link: 'https://github.com/HQCuong/polaris-vue' }],
  },
})
