import { fileURLToPath, URL } from 'node:url'

import { defineConfig, type HeadConfig } from 'vitepress'

// Generated by `scripts/generate-docs.mjs` — one VitePress sidebar *group* per
// component category (the same grouping shopify.dev uses), each holding the
// component reference pages under `docs/components/`. The codegen script owns
// this file wholesale, so nothing here needs touching beyond re-running
// `npm run docs:generate`.
import componentsSidebar from './components-sidebar.json'

// Public origin of the deployed docs. Used for canonical URLs, Open Graph tags,
// JSON-LD and the generated sitemap — keep it in sync with the Cloudflare route.
const SITE_URL = 'https://polaris-vue.vict0r.net'
const SITE_NAME = 'polaris-vue'
const SITE_DESCRIPTION =
  'Typed Vue 3 wrapper components for Shopify Polaris web components — props, events and v-model generated from the official Custom Elements Manifest.'
const OG_IMAGE = `${SITE_URL}/og.png`

// `relativePath` is the source file (`components/s-button.md`, `index.md`);
// with `cleanUrls` the public URL drops both `.md` and any trailing `index`.
function pageUrl(relativePath: string): string {
  const pathname = relativePath.replace(/(^|\/)index\.md$/, '$1').replace(/\.md$/, '')
  return `${SITE_URL}/${pathname}`
}

// https://vitepress.dev/reference/site-config
export default defineConfig({
  lang: 'en-US',
  title: SITE_NAME,
  description: SITE_DESCRIPTION,

  // Cloudflare Workers static assets 307-redirects `/foo.html` → `/foo`, so
  // emitting `.html` links would send every crawler hop through a redirect.
  // Clean URLs make the links VitePress writes match what Cloudflare serves.
  cleanUrls: true,

  // Git-based "last updated" per page; also feeds `<lastmod>` in the sitemap.
  lastUpdated: true,

  // Emits /sitemap.xml at build time from every routed page.
  sitemap: {
    hostname: SITE_URL,
  },

  // `docs/examples/*.md` are hand-written snippets that `generate-docs.mjs`
  // inlines into the component pages. They must live under `docs/` so the
  // demos can import from `./demos/`, but they are not pages — building them
  // would publish 60 duplicate-content URLs.
  srcExclude: ['examples/**'],

  head: [
    ['link', { rel: 'icon', href: '/favicon.ico' }],
    ['meta', { name: 'theme-color', content: '#008060' }],
    ['meta', { property: 'og:site_name', content: SITE_NAME }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:image', content: OG_IMAGE }],
    ['meta', { property: 'og:image:width', content: '1200' }],
    ['meta', { property: 'og:image:height', content: '630' }],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    ['meta', { name: 'twitter:image', content: OG_IMAGE }],
    // Loads the real Polaris custom element definitions so that live examples
    // in the docs (and the components used to render this site itself) work
    // exactly as they would in a consuming app.
    ['script', { src: 'https://cdn.shopify.com/shopifycloud/polaris.js' }],
  ],

  // Per-page tags that need the page's own title/description/URL: canonical,
  // Open Graph and Twitter. Site-wide static tags stay in `head` above.
  transformPageData(pageData, { siteConfig }) {
    const url = pageUrl(pageData.relativePath)
    const isHome = pageData.frontmatter.layout === 'home'
    const title = isHome
      ? `${pageData.title} | ${SITE_NAME}`
      : pageData.title === SITE_NAME
        ? SITE_NAME
        : `${pageData.title} | ${SITE_NAME}`
    const description = pageData.description || siteConfig.site.description

    const head: HeadConfig[] = [
      ['link', { rel: 'canonical', href: url }],
      ['meta', { property: 'og:url', content: url }],
      ['meta', { property: 'og:title', content: title }],
      ['meta', { property: 'og:description', content: description }],
      ['meta', { name: 'twitter:title', content: title }],
      ['meta', { name: 'twitter:description', content: description }],
    ]

    if (isHome) {
      head.push([
        'script',
        { type: 'application/ld+json' },
        JSON.stringify({
          '@context': 'https://schema.org',
          '@type': 'SoftwareSourceCode',
          name: SITE_NAME,
          description: SITE_DESCRIPTION,
          url: SITE_URL,
          codeRepository: 'https://github.com/HQCuong/polaris-vue',
          programmingLanguage: ['TypeScript', 'Vue'],
          runtimePlatform: 'Vue 3',
          license: 'https://opensource.org/licenses/MIT',
          keywords: 'shopify, polaris, web components, vue, vue 3, typescript',
        }),
      ])
    }

    pageData.frontmatter.head = [...(pageData.frontmatter.head ?? []), ...head]
  },

  vue: {
    template: {
      compilerOptions: {
        // Polaris web components (`<s-button>`, `<s-text-field>`, ...) are
        // custom elements, not Vue components — don't warn/resolve them as such.
        isCustomElement: (tag) => tag.startsWith('s-'),
      },
    },
  },

  vite: {
    resolve: {
      alias: {
        // Lets docs pages `import { SButton } from '@lib'` directly from source.
        '@lib': fileURLToPath(new URL('../../src/lib', import.meta.url)),
      },
    },
  },

  themeConfig: {
    // https://vitepress.dev/reference/default-theme-config
    nav: [
      { text: 'Guide', link: '/guide/getting-started' },
      { text: 'Components', link: '/components/' },
    ],

    sidebar: [
      {
        text: 'Guide',
        items: [
          { text: 'Getting started', link: '/guide/getting-started' },
          { text: 'Known quirks & gotchas', link: '/guide/quirks' },
          { text: 'All components', link: '/components/' },
        ],
      },
      // Spread rather than nested under a single "Components" parent: one more
      // level of nesting would push every component three deep and force two
      // clicks to reach any page.
      ...componentsSidebar,
    ],

    // Built-in MiniSearch index, built at build time from the full rendered text
    // of every page — so prop names, event names and prose are all searchable, not
    // just component titles. No external service, no runtime network call.
    search: {
      provider: 'local',
      options: {
        detailedView: true,
      },
    },

    outline: [2, 3],

    footer: {
      message: 'Released under the MIT License.',
      copyright: 'Wrappers around Shopify Polaris web components — not affiliated with Shopify.',
    },

    socialLinks: [{ icon: 'github', link: 'https://github.com/HQCuong/polaris-vue' }],
  },
})
