import { fileURLToPath, URL } from 'node:url'

import { defineConfig } from 'vitepress'

// Generated by `scripts/generate-docs.mjs` — a flat array of VitePress sidebar
// items (one per component reference page under `docs/components/`). Starts
// as an empty array here; the codegen script overwrites this file wholesale
// once component reference pages exist, so no changes are needed on this end
// beyond re-running `npm run docs:generate`.
import componentsSidebar from './components-sidebar.json'

// https://vitepress.dev/reference/site-config
export default defineConfig({
  title: 'polaris-vue',
  description: 'Typed Vue 3 wrapper components for Shopify Polaris web components.',

  head: [
    // Loads the real Polaris custom element definitions so that live examples
    // in the docs (and the components used to render this site itself) work
    // exactly as they would in a consuming app.
    ['script', { src: 'https://cdn.shopify.com/shopifycloud/polaris.js' }],
  ],

  // Component reference pages may not exist yet (they're generated by a
  // separate script), so avoid failing the build on links to them.
  ignoreDeadLinks: true,

  vue: {
    template: {
      compilerOptions: {
        // Polaris web components (`<s-button>`, `<s-text-field>`, ...) are
        // custom elements, not Vue components — don't warn/resolve them as such.
        isCustomElement: (tag) => tag.startsWith('s-'),
      },
    },
  },

  vite: {
    resolve: {
      alias: {
        // Lets docs pages `import { SButton } from '@lib'` directly from source.
        '@lib': fileURLToPath(new URL('../../src/lib', import.meta.url)),
      },
    },
  },

  themeConfig: {
    // https://vitepress.dev/reference/default-theme-config
    nav: [
      { text: 'Guide', link: '/guide/getting-started' },
      { text: 'Components', link: '/components/' },
    ],

    sidebar: [
      {
        text: 'Guide',
        items: [
          { text: 'Getting started', link: '/guide/getting-started' },
          { text: 'Known quirks & gotchas', link: '/guide/quirks' },
        ],
      },
      {
        text: 'Components',
        items: componentsSidebar,
      },
    ],

    socialLinks: [{ icon: 'github', link: 'https://github.com/HQCuong/polaris-vue' }],
  },
})
